/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/Alert.vue')['default']
    AppBar: typeof import('./components/AppBar.vue')['default']
    BarChart: typeof import('./components/PieChart.vue')['default']
    ExpenseAnalytics: typeof import('./components/ExpenseAnalytics.vue')['default']
    Home: typeof import('./components/Home.vue')['default']
    LineChart: typeof import('./components/LineChart.vue')['default']
    NewCategory: typeof import('./components/NewCategory.vue')['default']
    PieChart: typeof import('./components/PieChart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
