/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/bills/': RouteRecordInfo<'/bills/', '/bills', Record<never, never>, Record<never, never>>,
    '/bills/new': RouteRecordInfo<'/bills/new', '/bills/new', Record<never, never>, Record<never, never>>,
    '/categories/new': RouteRecordInfo<'/categories/new', '/categories/new', Record<never, never>, Record<never, never>>,
    '/expenses/': RouteRecordInfo<'/expenses/', '/expenses', Record<never, never>, Record<never, never>>,
    '/expenses/new': RouteRecordInfo<'/expenses/new', '/expenses/new', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/sallary': RouteRecordInfo<'/sallary', '/sallary', Record<never, never>, Record<never, never>>,
    '/sign-up': RouteRecordInfo<'/sign-up', '/sign-up', Record<never, never>, Record<never, never>>,
  }
}
